import type { Metadata } from "next";
import {  Geist_Mono,Figtree } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Foot from "@/components/ui/Footer";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body
        className={`${figtree.variable} ${geistMono.variable} relative antialiased bg-black`}
      >
        <Navbar/>
        {children}
        <Foot/>
      </body>
    </html>
  );
}
